# Generated by Django 6.0.2 on 2026-04-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tilte',
            new_name='title',
        ),
    ]
